### ISSUE TITLE
cannot run script

### ISSUE THREAD

**Issue by connected201** [TheDevFromKer/RDP-Brute#2]
hi, i have these errors:

root@node:~# cd RDP-Brute/
root@node:~/RDP-Brute# python start.py
  File "start.py", line 18
    async def connect(ip, user, password):
            ^
SyntaxError: invalid syntax
root@node:~/RDP-Brute# python start.py -h
  File "start.py", line 18
    async def connect(ip, user, password):
            ^
SyntaxError: invalid syntax
root@node:~/RDP-Brute# ./start.py
-bash: ./start.py: Permission denied
root@node:~/RDP-Brute# chmod +x start.py
root@node:~/RDP-Brute# ./start.py
./start.py: line 3: import: command not found
from: can't read /var/mail/async_timeout
from: can't read /var/mail/aiofiles
from: can't read /var/mail/platform
from: can't read /var/mail/asyncio
from: can't read /var/mail/asyncio.subprocess
./start.py: line 12: syntax error near unexpected token `=='
./start.py: line 12: `if sys_ver() == 'Windows':'
root@node:~/RDP-Brute# ./start.py
./start.py: line 3: import: command not found
from: can't read /var/mail/async_timeout
from: can't read /var/mail/aiofiles
from: can't read /var/mail/platform
from: can't read /var/mail/asyncio
from: can't read /var/mail/asyncio.subprocess
./start.py: line 12: syntax error near unexpected token `=='
./start.py: line 12: `if sys_ver() == 'Windows':'
root@node:~/RDP-Brute# python start.py
  File "start.py", line 18
    async def connect(ip, user, password):
            ^
SyntaxError: invalid syntax
i tried to run in different way, all dependencies was installed! Debina 9.8

**Comment by TheDevFromKer** [comment]
I think you have problem with Python.
Python must be >= 3.6.5 and `asyncio`, `aiofiles` is installed.
And make sure you run script by `python3`, not `python` (2.7)

**Comment by connected201** [comment]
root@node:~/rdp# pip install pathlib
Collecting pathlib
  Downloading https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 3.3MB/s
Building wheels for collected packages: pathlib
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: /root/.cache/pip/wheels/f9/b2/4a/68efdfe5093638a9918bd1bb734af625526e849487200aa171
Successfully built pathlib
Installing collected packages: pathlib
Successfully installed pathlib-1.0.1
root@node:~/rdp# pip install async_timeout
Collecting async_timeout
  Using cached https://files.pythonhosted.org/packages/23/6d/e37be168272b7a499111d0ed14940da80644d21b201e27980892c7125abb/async-timeout-2.0.1.tar.gz
Building wheels for collected packages: async-timeout
  Running setup.py bdist_wheel for async-timeout ... done
  Stored in directory: /root/.cache/pip/wheels/f0/79/c6/1554ade6ac5b86594929d0d1a9056be287545819e9e5c9466a
Successfully built async-timeout
Installing collected packages: async-timeout
Successfully installed async-timeout-2.0.1
root@node:~/rdp# python3.6 start.py
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    from async_timeout import timeout as ftime
ModuleNotFoundError: No module named 'async_timeout'
root@node:~/rdp# python3.6 start.py

root@node:~/rdp# python3.6 --version
Python 3.6.7
root@node:~/rdp#

i running using python3.6 start.py

so give error that ModuleNotFoundError: No module named 'async_timeout'

**Comment by TheDevFromKer** [comment]
Run: `pip3 install async-timeout`
Output must be:
```
$ pip3 install async-timeout
Collecting async-timeout
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Installing collected packages: async-timeout
Successfully installed async-timeout-3.0.1
```

**Comment by connected201** [comment]
root@node:~# pip3 install async-timeout
Collecting async-timeout
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Installing collected packages: async-timeout
Successfully installed async-timeout-3.0.1
root@node:~# cd rdp
root@node:~/rdp# python3.6 start.py
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    from async_timeout import timeout as ftime
ModuleNotFoundError: No module named 'async_timeout'
root@node:~/rdp# python3 start.py
  File "start.py", line 22
    r_agr = f"{fr_name} /v:{ip} /port:{port} /u:'{user}' " + \
                                                         ^
SyntaxError: invalid syntax
root@node:~/rdp#

**Comment by TheDevFromKer** [comment]
Show to me output of: `python3 --version`

**Comment by connected201** [comment]
> 
> 
> Show to me output of: `python3 --version`

 python3 --version
Python 3.5.3
root@node:~#
i know that i don't have installed  >= 3.6.5 but i running with python python3.6 
python3.6 --version
Python 3.6.7
root@node:~#
in kali is installed by default python 3.6?

**Comment by TheDevFromKer** [comment]
`python3.6 -m pip install asyncio aiofiles`
