### ISSUE TITLE
problemm running script in windows

### ISSUE THREAD

**Issue by connected201** [TheDevFromKer/RDP-Brute#3]
hi, i tried to run script in windows:
all dependencies was installed
OS: windows 10x64
![Q9yM0oGQmn](https://user-images.githubusercontent.com/20506433/60653340-88bb6480-9e52-11e9-97c1-02628e677440.png)

python version:
C:\Users\*****>python -V
Python 3.6.7
folder structure:
![image](https://user-images.githubusercontent.com/20506433/60650692-45aac280-9e4d-11e9-9bf0-0302b89a7aa3.png)

**Comment by TheDevFromKer** [comment]
Required Python 3.7 or wait update.
